// program must compile with the flag -D BUFFER_SIZE=xx
// which will be used as the buffer size for the read calls in your get_next_line.
// This value will be modified by your evaluators and by moulinette.

// gcc -Wall -Wextra -Werror -D BUFFER_SIZE=32 get_next_line.c get_next_line_utils.c