SRCS = Bureaucrat.cpp Form.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp main.cpp
NAME = Bureaucrat

all: $(NAME)

$(NAME):
	g++ -Wall -Werror -Wextra $(SRCS) -o $(NAME)

run:
	./$(NAME)

clean:
	rm -f $(NAME)